global_planning_node:
  ros__parameters:
    "map/resolution": 0.1
    "planning/step_size": 0.4
    "planning/h_surf_car": 0.7
    "planning/w_fit_plane": 1.0
    "planning/w_flatness": 1000.0
    "planning/w_slope": 0.1
    "planning/w_sparsity": 1.0
    "planning/ratio_max": 0.05
    "planning/ratio_min": 0.02
    "planning/conv_thre": 0.1152
    "planning/radius_fit_plane": 0.5
  
 



